### ISSUE TITLE
PV and PVC Instead of just Volumes

### ISSUE THREAD

**Issue by kferrone** [de-jcup/ekube#42]
In the view there is a section for `Volumes`. Confusing because I though it was the `Persistent Volumes`, but it is actually the `Persistent Volume Claims`. Maybe there could be both sections??

**Comment by de-jcup** [comment]
Are the claims not the only relevant parts or do you really need the PV info too?
Maybe I should just rename `Volumes` to `Volume claims` ?

**Comment by kferrone** [comment]
For debugging purposes, yes the persistent volumes and persistent volume claims both need to be shown. You don't need a provisioner on the StorageClass for persistent volumes and therefore they would need to be provisioned manually. When PVC uses a StorageClass the class could mess up and it would be nice to see the result of the claim. The persistent volumes contain the information about actually connecting to some source whereas the PVC is an abstraction from the type of volume it is. So in short the pv and pvc are different things but they are very much related.
