### ISSUE TITLE
Permissions Tollerance 

### ISSUE THREAD

**Issue by AndyDenning** [de-jcup/ekube#44]
Thanks to the changes implemented in "Handle errors on model build time #8" processing of fabric8 api continues even if a user doesn't have permissions on some particular resource in the cluster.  This means that the model is as fully populated as possible and anything that cannot be retrieved is marked as locked.

However there seems to be an issue with level of locking meaning that much of the information cannot be seen in the Kubernetes Explorer.

I have been connecting to a cluster whereby my user doesn't have permissions on networks.  However this leads to the whole namespace being marked as locked and thus I cannot see the services, deployments, pods etc.

I narrowed the issue to the DefaultSafeExecuter class.

 ```
   public <E extends EKubeElement, C, R> R execute(EKubeContext context, SafeExecutable<E, C, R> executable, E element, C client,
            ExecutionParameters parameters) {
        try {
            R result = executable.execute(context, client, element, parameters);
            afterExecution(context, executable, client, element, parameters);
            return result;
        } catch (Exception e) {
        	System.out.println(e.getMessage());
            /* NPE will be logged */
            if (e instanceof NullPointerException) {
            	
                context.getErrorHandler().logError("NPE occurred", e);
            }
            if (element instanceof AbstractEKubeElement) {
                AbstractEKubeElement ae = (AbstractEKubeElement) element;
                ae.setErrorMessage(e.getMessage());
                System.out.println("Would have locked " + ae.getName() + " " + ae.getLabel());
//                ae.setLocked(true);
            } else {
                context.getErrorHandler().logError("Kube element not wellknown, cannot set error and lock to :" + element, e);
            }
            return null;
        } 
    }
```
Note that I have commented the **ae.setLocked(true)** and this is now allowing me to see my full tree (but with networks empty).

Here are the logs generated from the code snippet:

```Failure executing: GET at: https://xxxxxx.xxx.xxxx/api/v1/nodes. Message: Forbidden! User exe-dev-1 doesn't have permission. nodes is forbidden: User "system:serviceaccount:xxx-yyy-1:xxx-yyy-1" cannot list nodes at the cluster scope.
Would have locked null Nodes
Failure executing: GET at: https://xxxxxx.xxx.xxxx/apis/networking.k8s.io/v1/namespaces/xxx-yyy-1/networkpolicies. Message: Forbidden! User xxx-yyy-1 doesn't have permission. networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:xxx-yyy-1:xxx-yyy-1" cannot list networkpolicies.networking.k8s.io in the namespace "xxx-yyy-1".
Would have locked xxx-yyy-1 xxx-yyy-1
Feb 11, 2019 9:10:43 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://xxxxxx.xxx.xxxx/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

It also seems like there is a memory leak somewhere.

**Comment by de-jcup** [comment]
I added own issue for the memory problem.

**Comment by de-jcup** [comment]
@AndyDenning The last commit should fix the problem with locked nodes not showing children.
I have currently not the possility to try out if this really fixes the problem.

Please try out if the fix is working and give me feedback.

**Comment by AndyDenning** [comment]
@de-jcup Almost worked but in addition I needed to make the same change in the ``getChildren`` method in the same class.
```
    public Object[] getChildren(Object parent) {
        if (parent instanceof EKubeContainer) {
            EKubeContainer container = (EKubeContainer) parent;
//            if (container.isLocked()) {
//                return new Object[0];
//            }
            return container.getChildren().toArray();
        }
        return new Object[0];
    }
```

**Comment by de-jcup** [comment]
@AndyDenning Thanx for review. Please try out again. If it works for you then please close the issue.

**Comment by AndyDenning** [comment]
That's working fine.  Thanks for the quick turnaround @de-jcup
