### ISSUE TITLE
Create possibility to launch interactive per mouse click

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/ekube#46]
Right mouse click on pod -> run interactive

get meta data
selfLink:
->
CALL : kubectl exec -it my-pod-id-xyz -- /bin/bash

**Comment by AndyDenning** [comment]
If you implement this, it would be worth thinking about allowing the exact command to be configured.  For example I have a script that allows me better behaviour using gitbash on windows environment.

`/usr/bin/mintty.exe --title ${p} -p @2 --hold always --window max --icon "C:\Program Files\Git\k8s.PNG.ico" --exec "/usr/bin/bash" --login -i -c " . ~/.profile; winpty kubectl exec -it ${p} -- bash"&`

This allows me to open a useful terminal window with title, icon and terminal settings.  ${p} being the pod name.

In addition I also have a similar script to open a window and tail logs:
`/usr/bin/mintty.exe --title ${p} -p @2 --hold always --window max --icon "C:\Program Files\Git\k8s.PNG.ico" --exec "/usr/bin/bash" --login -i -c " . ~/.profile; winpty kubectl  logs -f --tail=20 ${p}"&`

**Comment by de-jcup** [comment]
![Screenshot at 2019-07-18 18-53-57](https://user-images.githubusercontent.com/11644753/61477267-218fcb00-a98f-11e9-982c-90ecb9b80969.png)

**Comment by de-jcup** [comment]
Just released version 0.5.0 on marketplace with the feature.
