### ISSUE TITLE
Skip namespace search and used a namespace from .kube/config

### ISSUE THREAD

**Issue by GitOlsztyniak** [de-jcup/ekube#47]
I would like to see an enhancement where value of contexts.context.namespace is used without performing /api/v1/namespaces  call.

**Comment by de-jcup** [comment]
Hello @GitOlsztyniak , I am not sure how I shall solve this. I am a newbie at kubernetes and also in using the api, so please explain a bit more detailed please.

**Comment by GitOlsztyniak** [comment]
Let me check if I can find the place where the change needs to be done

**Comment by de-jcup** [comment]
With #60 there was a need to exactly do what proposed here. Will be done.

**Comment by de-jcup** [comment]
Just released version 0.8.0 on eclipse marketplace containing the changes.
