### ISSUE TITLE
Error connecting to the namespace AWS

### ISSUE THREAD

**Issue by lpignotti** [de-jcup/ekube#60]
Hi all,

I'm using the Spring Tools 4
File removed

Clicking on switch context and selecting my context I'm getting this error
File Removed

This is the stack trace
File Removed

The ekube plugin is configured correctly with the same config file using by kubectl
File Removed

**Comment by de-jcup** [comment]
I think the problem is, that your user has not the right to fetch the namespaces from your AWS K8 instance!

The last but one of your screenshots shows up the error message "...user-reader has not the permission: namespaces"

Please tryout if can do following inside your terminal:
```kubectl get namespaces```

You should get the same error message.

**Comment by de-jcup** [comment]
After reviewing the code the behaviour can be changed - currently even when namespace is already configured in kube config the namespaces are always listed (which is not necessary when ns is defined).

But when a context has no namespace setup (this can happen - e.g. on a staging environment) the namespace list should still be fetched ( so old behaviour for this case).

**Comment by de-jcup** [comment]
Just released version 0.8.0 on eclipse marketplace containing the changes.

**Comment by lpignotti** [comment]
Hi @de-jcup 

I have installed the 0.9.0 version

File Removed

I can confirm that I have configured in my Kube config the correct namespace for each contexts that I'm using.

File Removed

Yes you are right my user has not the permissions to browse the namespaces but I can browse the pods and services and read the log correctly

File Removed

Therefore, if I have understood correctly your fix, now that I have configured correctly the namespaces for each contexts on my kube config I should not receive the following error

File Removed

Do you think that I'm doing something wrong?

Thanks a lot for the support!!!

**Comment by de-jcup** [comment]
Sorry for late resonse, the issue was closed... so I did oversee it. In your commandline in line 2 you got the output:
"Error for server: (Forbidden) namespace is forbidden: user..... "
Can you even switch namespaces with this user?

**Comment by lpignotti** [comment]
Thanks for the support :-)

Using this user I cannot switch the namespace.

**Comment by de-jcup** [comment]
You removed the screenshots.

Please do me a favor if this still a problem:

1. Create a new issue (so it's clear there is still something to do)
2. Link this issue inside the new issue 
3. Provide error messages and/or screenshots
